models:
  - name: Gradient Boosting
    estimator: GradientBoostingClassifier
    parameters:
     - n_estimators
     - max_depth
     - learning_rate
    hyperparameter:
      n_estimators: 
        - 50
        - 100
        - 150
        - 200
        - 300
        - 400
        - 500
      max_depth: 
        - 3
        - 5
        - 7
        - 9
      learning_rate:
        - 0.01
        - 0.05
        - 0.1
        - 0.2
        - 1
  - name: Random Forest
    estimator: RandomForestClassifier
    parameters:
     - n_estimators
     - max_depth
     - min_samples_split
     - max_features
    hyperparameter:
      n_estimators: 
        - 50
        - 100
        - 150
        - 200
        - 300
        - 400
        - 500
      max_depth: 
        - 3
        - 5
        - 7
        - 9
      min_samples_split:
        - 3
        - 5
        - 7
        - 9
      max_features:
      - 'sqrt'
      - 'log2'
      - 
  - name: K Nearest Neighbour
    estimator: KNeighborsClassifier
    parameters:
     - n_neighbors
     - weights
     - metric
    hyperparameter:
      n_neighbors: 
        - 3
        - 5
        - 7
        - 9
        - 11
        - 13
        - 15
      weights: 
        - 'uniform'
        - 'distance'
      metric:
        - 'euclidean'
        - 'manhattan'
        - 'minkowski'
  - name: Support Vectors Classifier
    estimator: SVC
    parameters:
     - kernel
     - gamma
     - C
    hyperparameter:
      kernel: 
        - 'linear'
        - 'rbf'
        - 'sigmoid'
      gamma: 
        - 0.1
        - 1
        - 10
        - 100
      C:
        - 0.01
        - 0.1
        - 1
        - 10
  - name: Gaussian NB Classifier
    estimator: GaussianNB
    parameters:
      - var_smoothing
    hyperparameter:
      var_smoothing: 
        - 0.00001
        - 0.0001
        - 0.001
        - 0.01
        - 0.1

